name: tic_tac_toe_multiplayer
description: Multiplayer Tic Tac Toe with Firebase Auth & Firestore
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.1.6


  provider: ^6.1.2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true       # Generate Android launcher icons
  ios: false          # Disable iOS icon generation (optional, if you want to skip iOS)
  image_path: "assets/icon.png"  # Path to your icon image
