// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnPKG544FXymaQH6Ku67hrhmElUYly0U',
    appId: '1:932052524116:web:01f64f4e4e33be05dd61c1',
    messagingSenderId: '932052524116',
    projectId: 'auth-testing-862b1',
    authDomain: 'auth-testing-862b1.firebaseapp.com',
    storageBucket: 'auth-testing-862b1.firebasestorage.app',
    measurementId: 'G-VYCH0S5ZRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9J1O52PvHXtGuYhhNUUyiNw6DwK3oLw',
    appId: '1:932052524116:android:196e5a84010113b0dd61c1',
    messagingSenderId: '932052524116',
    projectId: 'auth-testing-862b1',
    storageBucket: 'auth-testing-862b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWd2H7xv3rAnaf1ZE97gjsZS9REpALj8c',
    appId: '1:932052524116:ios:fc1084a30057465cdd61c1',
    messagingSenderId: '932052524116',
    projectId: 'auth-testing-862b1',
    storageBucket: 'auth-testing-862b1.firebasestorage.app',
    androidClientId: '932052524116-48grlq4phsetvb5jjttghg1dvhlehukl.apps.googleusercontent.com',
    iosClientId: '932052524116-ck256ko0a3aj4eodl2lk1askle9mlf7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWd2H7xv3rAnaf1ZE97gjsZS9REpALj8c',
    appId: '1:932052524116:ios:fc1084a30057465cdd61c1',
    messagingSenderId: '932052524116',
    projectId: 'auth-testing-862b1',
    storageBucket: 'auth-testing-862b1.firebasestorage.app',
    androidClientId: '932052524116-48grlq4phsetvb5jjttghg1dvhlehukl.apps.googleusercontent.com',
    iosClientId: '932052524116-ck256ko0a3aj4eodl2lk1askle9mlf7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCnPKG544FXymaQH6Ku67hrhmElUYly0U',
    appId: '1:932052524116:web:01f64f4e4e33be05dd61c1',
    messagingSenderId: '932052524116',
    projectId: 'auth-testing-862b1',
    authDomain: 'auth-testing-862b1.firebaseapp.com',
    storageBucket: 'auth-testing-862b1.firebasestorage.app',
    measurementId: 'G-VYCH0S5ZRH',
  );
}
